repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-ast
    - id: check-case-conflict
    - id: check-symlinks
    - id: debug-statements
    - id: trailing-whitespace
    - id: mixed-line-ending
      args:
        - --fix=lf
    - id: end-of-file-fixer
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.17
    hooks:
    - id: isort
